# Default values for rails.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

buildconfig:
  enabled: true

git:
  sourceRepoUrl: https://github.com/pbuehl-redhat/rails-ex
  sourceRepoRef: master
  contextDir: /

database:
  user: hecarim
  password: Password1
  applicationUser: ezreal
  applicationPassword: Password1
  readinessProbe:
    timeoutSeconds: 1
    initialDelaySeconds: 5
  livenessProbe:
    timeoutSeconds: 10
    initialDelaySeconds: 120
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
    name: postgresql


istag:
  namespace: openshift
  postgresql:
    version: 12-el8

ruby:
  version: 3.1-ubi8
  gemmirror: ''

rails:
  env: production

readinessProbe:
  timeoutSeconds: 3
  initialDelaySeconds: 5
  path: "/articles"
  port: 8080

livenessProbe:
  timeoutSeconds: 3
  initialDelaySeconds: 10
  path: "/articles"
  port: 8080

image:
  repository: image-registry.openshift-image-registry.svc:5000/pbuehl-dev/rails-example@sha256:308d3d347f59d9434d31cffb33f3ade19776187450d1ee609b359e832e0d60ec
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: web

serviceAccount:
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

storage: 1Gi

route:
  enabled: true
  annotations:
        template.openshift.io/expose-uri: 'http://{.spec.host}{.spec.path}'
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: ''
  path: /
  tls: ''
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
