{{- if .Values.buildconfig.enabled -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "rails.fullname" . }}
  labels:
    {{- include "rails.labels" . | nindent 4 }}
{{- end }}
