kind: Secret
apiVersion: v1
metadata:
    name: postgresql
stringData:
    database-user: {{ .Values.database.user }}
    database-password: {{ .Values.database.password }}
    application-user: {{ .Values.database.applicationUser }}
    application-password: {{ .Values.database.applicationPassword }}
    keybase: {{ .Values.database.keybase | default (randAlphaNum 127) | b64enc }}