apiVersion: v1
kind: Service
metadata:
  name: postgresql
  annotations:
    description: Exposes the database server
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
      name: {{ .Values.database.service.name }}
  selector:
    name: postgresql
